### ISSUE TITLE
Discard calculated distances, use distance between GPS points instead

### ISSUE THREAD

**Issue by JeroenVanOmme** [gerhardol/globalsat-sporttracks-plugin#6] opened 2015-07-06 06:19 UTC
Hi Gerhard,

as requested a new issue in Github.
In response to your questions:
- If you look at the fitlog, there is a element 
<DistanceMeters>33477</DistanceMeters>
However looking at the last indididual point
<DistanceMeters>28935.169921875</DistanceMeters>
It is the distance calculated in the individual trackpoints that seems incorrect

My workflow: Import using the Globalsat-plug-in, Sync to ST.mobi.
I would then use Tapiriik to sync with Strava, but Strava does not use the summary data, but the calculated values, so my data on Strava look far worse than it really is.
Because of this, I now manually export from ST.mobi to TCX, convert this using TCXTools.com, then upload this to Strava, so this will show the same results as the ST.mobi summary..

I will try tour suggetion of using the Manual Calculations option in ST, but I suspect the data is already "wrong" in the watch and i doubt ST will do anything about it....

Having the option of recalculation distances based solely on GPS-point in the settingspage of the plug-in would be a acceptable solution for me.

**Comment by JeroenVanOmme** [comment] 2015-07-06 11:10
Hmm.. seems the github editor has filtered some of my text.
Where it says 33477, it should be surrounded by a tag called "DistanceMeters".
PS. this is line 8 in the file.

**Comment by gerhardol** [comment] 2015-07-23 21:29
Start of discussion:
https://code.google.com/p/globalsat-sporttracks-plugin/issues/detail?id=6

The distance calculation is calculated from the speed/pace data in the device.
It is not possible to find the source of the Speed/Distance data. In GB-580P this is often the speed sensor, more accurate than GPS.
It may be that the reported pace is off for some reason. Nothing I have seen, but I have not used the 625xt for some time (crappy HR).
Most programs do not care about the device distance, this is visible in for instance Trails plugin, to see the device view of the pace.

If the problem is that Strava uses the Distance track, then you can go to Edit-DataTracks, select Distance, mark all points, then delete the points.

An automated solution could be to delete all points after importing (probably add to MiscPlugin, usable for existing activities), or an option when importing. in the Globalsat plugin (should be on for GB-580P at least.)

**Comment by JeroenVanOmme** [comment] 2015-08-07 07:14
Hello Gerhard,

sorry for not getting back to you earlier.
My ideal solution would be if the plug-in would ignore the calculated
differences between the individual GPS point and just recalculate it using
the haversine formula. This way, the problem is corrected almost at the
source and any following processes, such as elevation correction, exporting
to mobi, syncing with Strava, would be performed on this more accurate data
aswell.

Hope this helps.
PS. I am a developer by profession but have almost 0 exprience with C#
otherwise I'd have tried to make such a thing myself :-)

PPS. I really appreciate you taking the time to help me analyse this issue!

Jeroen


2015-07-23 23:29 GMT+02:00 Gerhard Olsson <notifications@github.com>:

**Comment by gerhardol** [comment] 2015-08-07 21:28
I added an option to allow skipping importing the Distance information from the Globalsat device.
With that, there is no need to remove the distance information after importing.
See Releases.
Please report when done, so the plugin can be updated in ST. (My Globalsat devices are broken or unusable.)

Recalculating a new distance track is a separate plugin. The distance track is normally not used at all in Sporttracks or any other software (other than Garmin and supposedly Strava). Normallly, using the distance track is confusing, as most SW uses GPS info, only the distance if no GPS.

**Comment by JeroenVanOmme** [comment] 2015-08-13 12:06
Hello Gerhard,

sorry to inform you that the new option doesn't appear to do anything.
I loaded a work-out with both the option on and off, but there is no
difference (the fitlogs are identical apart from Activity and Metadata
values, which is expected).
If needed I can provide you with more data, just let me know.

Jeroen


2015-08-07 23:28 GMT+02:00 Gerhard Olsson <notifications@github.com>:

**Comment by gerhardol** [comment] 2015-08-14 19:57
Sorry, bad implementation. My devices are not working well, I made some changes that I could not test.
(Done that now.)

**Comment by JeroenVanOmme** [comment] 2015-08-15 11:14
Could you compile this version so I can test it?
Thanks!
Op 14 aug. 2015 21:57 schreef "Gerhard Olsson" <notifications@github.com>:

**Comment by JeroenVanOmme** [comment] 2015-08-15 11:14
Could you compile this version so I can test it?
Thanks!
Op 14 aug. 2015 21:57 schreef "Gerhard Olsson" <notifications@github.com>:

Sorry, bad implementation. My devices are not working well, I made some
changes that I could not test.
(Done that now.)

—
Reply to this email directly or view it on GitHub
<https://github.com/gerhardol/globalsat-sporttracks-plugin/issues/6#issuecomment-131219955>
.

**Comment by gerhardol** [comment] 2015-08-15 11:16
Sorry forgot to upload. Tomorrow, away over the weekend.
Den 15 aug 2015 1:14 em skrev "JeroenVanOmme" <notifications@github.com>:
>
> Could you compile this version so I can test it?
> Thanks!
> Op 14 aug. 2015 21:57 schreef "Gerhard Olsson" <notifications@github.com>:
>
> > Sorry, bad implementation. My devices are not working well, I made some
> > changes that I could not test.
> > (Done that now.)
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/gerhardol/globalsat-sporttracks-plugin/issues/6#issuecomment-131219955

**Comment by gerhardol** [comment] 2015-08-16 15:23
Build uploaded

**Comment by JeroenVanOmme** [comment] 2015-08-17 19:53
Hi Gerhard,

happy to report that the new version works. Thanks for the time you spent
on this issue!

Jeroen

2015-08-16 17:23 GMT+02:00 Gerhard Olsson <notifications@github.com>:

**Comment by gerhardol** [comment] 2015-08-17 19:58
I will close the issue then.
Will probably wait a little before releasing in plugin catalog, there were a question about 625M recently in the forum.
The question about haversine should be supported if ST uses the distance track before GPS in ST core (again, it was briefly supported years ago).

**Closed by gerhardol** 2015-08-17 19:58 UTC
